import { columns, Payment } from "./columns";
import { DataTable } from "./data-table";

export const payments: Payment[] = [
  {
    id: "c8b39",
    amount: 545,
    status: "pending",
    name: "Fatma Adel",
    email: "fatma0@demo.org",
  },
  {
    id: "b2bf4",
    amount: 767,
    status: "failed",
    name: "Khalid Mansour",
    email: "khalid1@example.com",
  },
  {
    id: "20c91",
    amount: 287,
    status: "success",
    name: "Khalid Mansour",
    email: "khalid2@test.com",
  },
  {
    id: "7e77d",
    amount: 772,
    status: "failed",
    name: "Ahmed Noor",
    email: "ahmed3@example.com",
  },
  {
    id: "3590b",
    amount: 517,
    status: "success",
    name: "Ahmed Noor",
    email: "ahmed4@test.com",
  },
  {
    id: "8b2f6",
    amount: 652,
    status: "pending",
    name: "Sara Ali",
    email: "sara5@mail.com",
  },
  {
    id: "f19e4",
    amount: 143,
    status: "success",
    name: "Mona Youssef",
    email: "mona6@test.com",
  },
  {
    id: "d7a34",
    amount: 935,
    status: "failed",
    name: "Mohamed Salem",
    email: "mohamed7@example.com",
  },
  {
    id: "4c9a1",
    amount: 884,
    status: "pending",
    name: "Nourhan Fathi",
    email: "nourhan8@demo.org",
  },
  {
    id: "5aef3",
    amount: 237,
    status: "success",
    name: "Hassan Ibrahim",
    email: "hassan9@test.com",
  },
  {
    id: "6b293",
    amount: 364,
    status: "failed",
    name: "Fatma Adel",
    email: "fatma10@example.com",
  },
  {
    id: "7c941",
    amount: 921,
    status: "pending",
    name: "Sara Ali",
    email: "sara11@test.com",
  },
  {
    id: "8d582",
    amount: 415,
    status: "success",
    name: "Khalid Mansour",
    email: "khalid12@demo.org",
  },
  {
    id: "9e6a7",
    amount: 786,
    status: "failed",
    name: "Mona Youssef",
    email: "mona13@mail.com",
  },
  {
    id: "af719",
    amount: 652,
    status: "pending",
    name: "Ahmed Noor",
    email: "ahmed14@test.com",
  },
  {
    id: "b8623",
    amount: 298,
    status: "success",
    name: "Sara Ali",
    email: "sara15@example.com",
  },
  {
    id: "c9318",
    amount: 845,
    status: "failed",
    name: "Fatma Adel",
    email: "fatma16@demo.org",
  },
  {
    id: "da421",
    amount: 153,
    status: "pending",
    name: "Hassan Ibrahim",
    email: "hassan17@mail.com",
  },
  {
    id: "eb531",
    amount: 762,
    status: "success",
    name: "Mohamed Salem",
    email: "mohamed18@test.com",
  },
  {
    id: "fc641",
    amount: 645,
    status: "failed",
    name: "Layla Hassan",
    email: "layla19@example.com",
  },
  {
    id: "ad751",
    amount: 923,
    status: "pending",
    name: "Nourhan Fathi",
    email: "nourhan20@demo.org",
  },
  {
    id: "be862",
    amount: 112,
    status: "success",
    name: "Sara Ali",
    email: "sara21@test.com",
  },
  {
    id: "cf973",
    amount: 453,
    status: "failed",
    name: "Khalid Mansour",
    email: "khalid22@example.com",
  },
  {
    id: "d0a84",
    amount: 739,
    status: "pending",
    name: "Fatma Adel",
    email: "fatma23@test.com",
  },
  {
    id: "e1b95",
    amount: 334,
    status: "success",
    name: "Hassan Ibrahim",
    email: "hassan24@demo.org",
  },
  {
    id: "f2ca6",
    amount: 920,
    status: "failed",
    name: "Mona Youssef",
    email: "mona25@mail.com",
  },
  {
    id: "03db7",
    amount: 275,
    status: "pending",
    name: "Ahmed Noor",
    email: "ahmed26@test.com",
  },
  {
    id: "14ec8",
    amount: 816,
    status: "success",
    name: "Nourhan Fathi",
    email: "nourhan27@demo.org",
  },
  {
    id: "25fd9",
    amount: 472,
    status: "failed",
    name: "Sara Ali",
    email: "sara28@mail.com",
  },
  {
    id: "3610a",
    amount: 689,
    status: "pending",
    name: "Fatma Adel",
    email: "fatma29@test.com",
  },
  {
    id: "4721b",
    amount: 153,
    status: "success",
    name: "Mohamed Salem",
    email: "mohamed30@example.com",
  },
  {
    id: "5832c",
    amount: 731,
    status: "failed",
    name: "Khalid Mansour",
    email: "khalid31@test.com",
  },
  {
    id: "6943d",
    amount: 208,
    status: "pending",
    name: "Sara Ali",
    email: "sara32@demo.org",
  },
  {
    id: "7a54e",
    amount: 947,
    status: "success",
    name: "Fatma Adel",
    email: "fatma33@mail.com",
  },
  {
    id: "8b65f",
    amount: 329,
    status: "failed",
    name: "Nourhan Fathi",
    email: "nourhan34@test.com",
  },
  {
    id: "9c670",
    amount: 890,
    status: "pending",
    name: "Hassan Ibrahim",
    email: "hassan35@demo.org",
  },
  {
    id: "ad781",
    amount: 431,
    status: "success",
    name: "Mona Youssef",
    email: "mona36@test.com",
  },
  {
    id: "be892",
    amount: 678,
    status: "failed",
    name: "Ahmed Noor",
    email: "ahmed37@mail.com",
  },
  {
    id: "cf9a3",
    amount: 512,
    status: "pending",
    name: "Sara Ali",
    email: "sara38@example.com",
  },
  {
    id: "d0ab4",
    amount: 733,
    status: "success",
    name: "Fatma Adel",
    email: "fatma39@test.com",
  },
  {
    id: "e1bc5",
    amount: 384,
    status: "failed",
    name: "Nourhan Fathi",
    email: "nourhan40@demo.org",
  },
  {
    id: "f2cd6",
    amount: 609,
    status: "pending",
    name: "Hassan Ibrahim",
    email: "hassan41@test.com",
  },
  {
    id: "03de7",
    amount: 972,
    status: "success",
    name: "Layla Hassan",
    email: "layla42@example.com",
  },
  {
    id: "14ef8",
    amount: 246,
    status: "failed",
    name: "Mona Youssef",
    email: "mona43@test.com",
  },
  {
    id: "25f09",
    amount: 877,
    status: "pending",
    name: "Sara Ali",
    email: "sara44@mail.com",
  },
  {
    id: "3611a",
    amount: 569,
    status: "success",
    name: "Fatma Adel",
    email: "fatma45@demo.org",
  },
];

export default function Payments() {
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Payments</h1>
      </div>

      <DataTable columns={columns} data={payments} />
    </div>
  );
}
